<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace>DX11_Samples</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="glTF2Loader" Version="2.0.0" />
		<PackageReference Include="ImGui.NET" Version="1.91.6.1" />
		<PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.333">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Vortice.D3DCompiler" Version="3.8.3" />
		<PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />
		<PackageReference Include="Vortice.DXGI" Version="3.8.3" />
	</ItemGroup>

	<ItemGroup>
		<None Update="fat-man-a.glb">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="KnightCharacter.glb">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Pixel.hlsl">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Model.glb">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Spider.glb">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="TestScene.json">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Vertex.hlsl">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>


